In [1]:
%pwd

'/home/sunghyun/oneview-backend/oneview-backend_0608'

In [2]:
import sqlalchemy
from sqlalchemy import create_engine, func, select, case, between
from sqlalchemy.orm import sessionmaker
from app import models

SQLALCHEMY_DATABASE_URL = "oracle+cx_oracle://nwai:nwai123@10.203.13.202:8316/?service_name=xe&encoding=UTF-8&nencoding=UTF-8"

engine = create_engine(
    SQLALCHEMY_DATABASE_URL,
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
db = SessionLocal()

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!

In [207]:
query = """
select (nvl(wjxbfs2, 0)), equip_nm from dashboard_volte_dd
where equip_nm='상대원동_오리엔트시계_32T_A'
"""
db.execute(query).all()

[(1, '상대원동_오리엔트시계_32T_A'),
 (16, '상대원동_오리엔트시계_32T_A'),
 (10, '상대원동_오리엔트시계_32T_A')]

In [209]:
que = select(func.sum(func.nvl(models.Volte.wjxbfs2, 0)), models.Volte.equip_nm).\
where(models.Volte.equip_nm == "상대원동_오리엔트시계_32T_A").group_by(models.Volte.equip_nm)
db.execute(que).all()

[(27, '상대원동_오리엔트시계_32T_A')]

In [237]:
sum_try = func.sum(func.nvl(models.Volte.wjxbfs1, 0.0))
sum_suc = func.sum(func.nvl(models.Volte.wjxbfs2, 0.0))
sum_fail = func.sum(func.nvl(models.Volte.wjxbfs3, 0.0))
sum_cut = func.sum(func.nvl(models.Volte.wjxbfs4, 0.0))
cut_ratio = func.sum(func.nvl(models.Volte.wjxbfs4, 0.0)) / (func.sum(func.nvl(models.Volte.wjxbfs2, 0)) + 1e-6) * 100
cut_ratio = func.round(cut_ratio, 4)
cut_ratio = func.coalesce(cut_ratio, 0.0000).label("cut_ratio")
juso = func.concat(models.Volte.sido_nm, models.Volte.eup_myun_dong_nm).label("juso")
entities = [
    models.Volte.equip_nm,
    juso,
    models.Volte.oper_team_nm,
    models.Volte.area_jo_nm1,
    sum_try,
    sum_suc,
    sum_fail,
    sum_cut,
    cut_ratio
]

In [244]:
help(stmt)

Help on Select in module sqlalchemy.sql.selectable object:

class Select(HasPrefixes, HasSuffixes, HasHints, sqlalchemy.sql.base.HasCompileState, DeprecatedSelectGenerations, _SelectFromElements, GenerativeSelect)
 |  Represents a ``SELECT`` statement.
 |
 |  The :class:`_sql.Select` object is normally constructed using the
 |  :func:`_sql.select` function.  See that function for details.
 |
 |  .. seealso::
 |
 |      :func:`_sql.select`
 |
 |      :ref:`coretutorial_selecting` - in the 1.x tutorial
 |
 |      :ref:`tutorial_selecting_data` - in the 2.0 tutorial
 |
 |  Method resolution order:
 |      Select
 |      HasPrefixes
 |      HasSuffixes
 |      HasHints
 |      sqlalchemy.sql.base.HasCompileState
 |      DeprecatedSelectGenerations
 |      _SelectFromElements
 |      GenerativeSelect
 |      DeprecatedSelectBaseGenerations
 |      SelectBase
 |      sqlalchemy.sql.roles.SelectStatementRole
 |      sqlalchemy.sql.roles.DMLSelectRole
 |      sqlalchemy.sql.roles.CompoundElementRole
 |      sqlalchemy.sql.roles.AllowsLambdaRole
 |      sqlalchemy.sql.roles.InElementRole
 |      HasCTE
 |      sqlalchemy.sql.roles.HasCTERole
 |      sqlalchemy.sql.base.Executable
 |      sqlalchemy.sql.roles.StatementRole
 |      sqlalchemy.sql.annotation.SupportsCloneAnnotations
 |      Selectable
 |      ReturnsRows
 |      sqlalchemy.sql.roles.ReturnsRowsRole
 |      sqlalchemy.sql.elements.ClauseElement
 |      sqlalchemy.sql.roles.SQLRole
 |      sqlalchemy.sql.base.Generative
 |      sqlalchemy.sql.annotation.SupportsWrappingAnnotations
 |      sqlalchemy.sql.annotation.SupportsAnnotations
 |      sqlalchemy.sql.traversals.MemoizedHasCacheKey
 |      sqlalchemy.sql.traversals.HasCacheKey
 |      sqlalchemy.util.langhelpers.HasMemoized
 |      sqlalchemy.sql.traversals.HasCopyInternals
 |      sqlalchemy.sql.visitors.Traversible
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  add_columns(self, *columns)
 |      Return a new :func:`_expression.select` construct with
 |      the given column expressions added to its columns clause.
 |
 |      E.g.::
 |
 |          my_select = my_select.add_columns(table.c.new_column)
 |
 |      See the documentation for
 |      :meth:`_expression.Select.with_only_columns`
 |      for guidelines on adding /replacing the columns of a
 |      :class:`_expression.Select` object.
 |
 |  column(self, column)
 |      Return a new :func:`_expression.select` construct with
 |      the given column expression added to its columns clause.
 |
 |      .. deprecated:: 1.4 The :meth:`_expression.Select.column` method is deprecated and will be removed in a future release.  Please use :meth:`_expression.Select.add_columns`
 |
 |      E.g.::
 |
 |          my_select = my_select.column(table.c.new_column)
 |
 |      See the documentation for
 |      :meth:`_expression.Select.with_only_columns`
 |      for guidelines on adding /replacing the columns of a
 |      :class:`_expression.Select` object.
 |
 |  correlate(self, *fromclauses)
 |      Return a new :class:`_expression.Select`
 |      which will correlate the given FROM
 |      clauses to that of an enclosing :class:`_expression.Select`.
 |
 |      Calling this method turns off the :class:`_expression.Select` object's
 |      default behavior of "auto-correlation".  Normally, FROM elements
 |      which appear in a :class:`_expression.Select`
 |      that encloses this one via
 |      its :term:`WHERE clause`, ORDER BY, HAVING or
 |      :term:`columns clause` will be omitted from this
 |      :class:`_expression.Select`
 |      object's :term:`FROM clause`.
 |      Setting an explicit correlation collection using the
 |      :meth:`_expression.Select.correlate`
 |      method provides a fixed list of FROM objects
 |      that can potentially take place in this process.
 |
 |      When :meth:`_expression.Select.correlate`
 |      is used to apply specific FROM clauses
 |      for correlation, the FROM elements become candidates for
 |      correlation regardless of how deeply nested this
 |      :class:`_expression.Select`
 |      object is, relative to an enclosing :class:`_expression.Select`
 |      which refers to
 |      the same FROM object.  This is in contrast to the behavior of
 |      "auto-correlation" which only correlates to an immediate enclosing
 |      :class:`_expression.Select`.
 |      Multi-level correlation ensures that the link
 |      between enclosed and enclosing :class:`_expression.Select`
 |      is always via
 |      at least one WHERE/ORDER BY/HAVING/columns clause in order for
 |      correlation to take place.
 |
 |      If ``None`` is passed, the :class:`_expression.Select`
 |      object will correlate
 |      none of its FROM entries, and all will render unconditionally
 |      in the local FROM clause.
 |
 |      :param \*fromclauses: a list of one or more
 |       :class:`_expression.FromClause`
 |       constructs, or other compatible constructs (i.e. ORM-mapped
 |       classes) to become part of the correlate collection.
 |
 |      .. seealso::
 |
 |          :meth:`_expression.Select.correlate_except`
 |
 |          :ref:`correlated_subqueries`
 |
 |  correlate_except(self, *fromclauses)
 |      Return a new :class:`_expression.Select`
 |      which will omit the given FROM
 |      clauses from the auto-correlation process.
 |
 |      Calling :meth:`_expression.Select.correlate_except` turns off the
 |      :class:`_expression.Select` object's default behavior of
 |      "auto-correlation" for the given FROM elements.  An element
 |      specified here will unconditionally appear in the FROM list, while
 |      all other FROM elements remain subject to normal auto-correlation
 |      behaviors.
 |
 |      If ``None`` is passed, the :class:`_expression.Select`
 |      object will correlate
 |      all of its FROM entries.
 |
 |      :param \*fromclauses: a list of one or more
 |       :class:`_expression.FromClause`
 |       constructs, or other compatible constructs (i.e. ORM-mapped
 |       classes) to become part of the correlate-exception collection.
 |
 |      .. seealso::
 |
 |          :meth:`_expression.Select.correlate`
 |
 |          :ref:`correlated_subqueries`
 |
 |  distinct(self, *expr)
 |      Return a new :func:`_expression.select` construct which
 |      will apply DISTINCT to its columns clause.
 |
 |      :param \*expr: optional column expressions.  When present,
 |       the PostgreSQL dialect will render a ``DISTINCT ON (<expressions>>)``
 |       construct.
 |
 |       .. deprecated:: 1.4 Using \*expr in other dialects is deprecated
 |          and will raise :class:`_exc.CompileError` in a future version.
 |
 |  except_(self, *other, **kwargs)
 |      Return a SQL ``EXCEPT`` of this select() construct against
 |      the given selectable provided as positional arguments.
 |
 |      :param \*other: one or more elements with which to create a
 |       UNION.
 |
 |       .. versionchanged:: 1.4.28
 |
 |          multiple elements are now accepted.
 |
 |      :param \**kwargs: keyword arguments are forwarded to the constructor
 |       for the newly created :class:`_sql.CompoundSelect` object.
 |
 |  except_all(self, *other, **kwargs)
 |      Return a SQL ``EXCEPT ALL`` of this select() construct against
 |      the given selectables provided as positional arguments.
 |
 |      :param \*other: one or more elements with which to create a
 |       UNION.
 |
 |       .. versionchanged:: 1.4.28
 |
 |          multiple elements are now accepted.
 |
 |      :param \**kwargs: keyword arguments are forwarded to the constructor
 |       for the newly created :class:`_sql.CompoundSelect` object.
 |
 |  filter(self, *criteria)
 |      A synonym for the :meth:`_future.Select.where` method.
 |
 |  filter_by(self, **kwargs)
 |      apply the given filtering criterion as a WHERE clause
 |      to this select.
 |
 |  from_statement(self, statement)
 |      Apply the columns which this :class:`.Select` would select
 |      onto another statement.
 |
 |      This operation is :term:`plugin-specific` and will raise a not
 |      supported exception if this :class:`_sql.Select` does not select from
 |      plugin-enabled entities.
 |
 |
 |      The statement is typically either a :func:`_expression.text` or
 |      :func:`_expression.select` construct, and should return the set of
 |      columns appropriate to the entities represented by this
 |      :class:`.Select`.
 |
 |      .. seealso::
 |
 |          :ref:`orm_queryguide_selecting_text` - usage examples in the
 |          ORM Querying Guide
 |
 |  get_children(self, **kwargs)
 |      Return immediate child :class:`.visitors.Traversible`
 |      elements of this :class:`.visitors.Traversible`.
 |
 |      This is used for visit traversal.
 |
 |      \**kw may contain flags that change the collection that is
 |      returned, for example to return a subset of items in order to
 |      cut down on larger traversals, or to return child items from a
 |      different context (such as schema-level collections instead of
 |      clause-level).
 |
 |  get_final_froms(self)
 |      Compute the final displayed list of :class:`_expression.FromClause`
 |      elements.
 |
 |      This method will run through the full computation required to
 |      determine what FROM elements will be displayed in the resulting
 |      SELECT statement, including shadowing individual tables with
 |      JOIN objects, as well as full computation for ORM use cases including
 |      eager loading clauses.
 |
 |      For ORM use, this accessor returns the **post compilation**
 |      list of FROM objects; this collection will include elements such as
 |      eagerly loaded tables and joins.  The objects will **not** be
 |      ORM enabled and not work as a replacement for the
 |      :meth:`_sql.Select.select_froms` collection; additionally, the
 |      method is not well performing for an ORM enabled statement as it
 |      will incur the full ORM construction process.
 |
 |      To retrieve the FROM list that's implied by the "columns" collection
 |      passed to the :class:`_sql.Select` originally, use the
 |      :attr:`_sql.Select.columns_clause_froms` accessor.
 |
 |      To select from an alternative set of columns while maintaining the
 |      FROM list, use the :meth:`_sql.Select.with_only_columns` method and
 |      pass the
 |      :paramref:`_sql.Select.with_only_columns.maintain_column_froms`
 |      parameter.
 |
 |      .. versionadded:: 1.4.23 - the :meth:`_sql.Select.get_final_froms`
 |         method replaces the previous :attr:`_sql.Select.froms` accessor,
 |         which is deprecated.
 |
 |      .. seealso::
 |
 |          :attr:`_sql.Select.columns_clause_froms`
 |
 |  having(self, having)
 |      Return a new :func:`_expression.select` construct with
 |      the given expression added to
 |      its HAVING clause, joined to the existing clause via AND, if any.
 |
 |  intersect(self, *other, **kwargs)
 |      Return a SQL ``INTERSECT`` of this select() construct against
 |      the given selectables provided as positional arguments.
 |
 |      :param \*other: one or more elements with which to create a
 |       UNION.
 |
 |       .. versionchanged:: 1.4.28
 |
 |          multiple elements are now accepted.
 |
 |      :param \**kwargs: keyword arguments are forwarded to the constructor
 |       for the newly created :class:`_sql.CompoundSelect` object.
 |
 |  intersect_all(self, *other, **kwargs)
 |      Return a SQL ``INTERSECT ALL`` of this select() construct
 |      against the given selectables provided as positional arguments.
 |
 |      :param \*other: one or more elements with which to create a
 |       UNION.
 |
 |       .. versionchanged:: 1.4.28
 |
 |          multiple elements are now accepted.
 |
 |      :param \**kwargs: keyword arguments are forwarded to the constructor
 |       for the newly created :class:`_sql.CompoundSelect` object.
 |
 |  is_derived_from(self, fromclause)
 |
 |  join(self, target, onclause=None, isouter=False, full=False)
 |      Create a SQL JOIN against this :class:`_expression.Select`
 |      object's criterion
 |      and apply generatively, returning the newly resulting
 |      :class:`_expression.Select`.
 |
 |      E.g.::
 |
 |          stmt = select(user_table).join(address_table, user_table.c.id == address_table.c.user_id)
 |
 |      The above statement generates SQL similar to::
 |
 |          SELECT user.id, user.name FROM user JOIN address ON user.id = address.user_id
 |
 |      .. versionchanged:: 1.4 :meth:`_expression.Select.join` now creates
 |         a :class:`_sql.Join` object between a :class:`_sql.FromClause`
 |         source that is within the FROM clause of the existing SELECT,
 |         and a given target :class:`_sql.FromClause`, and then adds
 |         this :class:`_sql.Join` to the FROM clause of the newly generated
 |         SELECT statement.    This is completely reworked from the behavior
 |         in 1.3, which would instead create a subquery of the entire
 |         :class:`_expression.Select` and then join that subquery to the
 |         target.
 |
 |         This is a **backwards incompatible change** as the previous behavior
 |         was mostly useless, producing an unnamed subquery rejected by
 |         most databases in any case.   The new behavior is modeled after
 |         that of the very successful :meth:`_orm.Query.join` method in the
 |         ORM, in order to support the functionality of :class:`_orm.Query`
 |         being available by using a :class:`_sql.Select` object with an
 |         :class:`_orm.Session`.
 |
 |         See the notes for this change at :ref:`change_select_join`.
 |
 |
 |      :param target: target table to join towards
 |
 |      :param onclause: ON clause of the join.  If omitted, an ON clause
 |       is generated automatically based on the :class:`_schema.ForeignKey`
 |       linkages between the two tables, if one can be unambiguously
 |       determined, otherwise an error is raised.
 |
 |      :param isouter: if True, generate LEFT OUTER join.  Same as
 |       :meth:`_expression.Select.outerjoin`.
 |
 |      :param full: if True, generate FULL OUTER join.
 |
 |      .. seealso::
 |
 |          :ref:`tutorial_select_join` - in the :doc:`/tutorial/index`
 |
 |          :ref:`orm_queryguide_joins` - in the :ref:`queryguide_toplevel`
 |
 |          :meth:`_expression.Select.join_from`
 |
 |          :meth:`_expression.Select.outerjoin`
 |
 |  join_from(self, from_, target, onclause=None, isouter=False, full=False)
 |      Create a SQL JOIN against this :class:`_expression.Select`
 |      object's criterion
 |      and apply generatively, returning the newly resulting
 |      :class:`_expression.Select`.
 |
 |      E.g.::
 |
 |          stmt = select(user_table, address_table).join_from(
 |              user_table, address_table, user_table.c.id == address_table.c.user_id
 |          )
 |
 |      The above statement generates SQL similar to::
 |
 |          SELECT user.id, user.name, address.id, address.email, address.user_id
 |          FROM user JOIN address ON user.id = address.user_id
 |
 |      .. versionadded:: 1.4
 |
 |      :param from\_: the left side of the join, will be rendered in the
 |       FROM clause and is roughly equivalent to using the
 |       :meth:`.Select.select_from` method.
 |
 |      :param target: target table to join towards
 |
 |      :param onclause: ON clause of the join.
 |
 |      :param isouter: if True, generate LEFT OUTER join.  Same as
 |       :meth:`_expression.Select.outerjoin`.
 |
 |      :param full: if True, generate FULL OUTER join.
 |
 |      .. seealso::
 |
 |          :ref:`tutorial_select_join` - in the :doc:`/tutorial/index`
 |
 |          :ref:`orm_queryguide_joins` - in the :ref:`queryguide_toplevel`
 |
 |          :meth:`_expression.Select.join`
 |
 |  outerjoin(self, target, onclause=None, full=False)
 |      Create a left outer join.
 |
 |      Parameters are the same as that of :meth:`_expression.Select.join`.
 |
 |      .. versionchanged:: 1.4 :meth:`_expression.Select.outerjoin` now
 |         creates a :class:`_sql.Join` object between a
 |         :class:`_sql.FromClause` source that is within the FROM clause of
 |         the existing SELECT, and a given target :class:`_sql.FromClause`,
 |         and then adds this :class:`_sql.Join` to the FROM clause of the
 |         newly generated SELECT statement.    This is completely reworked
 |         from the behavior in 1.3, which would instead create a subquery of
 |         the entire
 |         :class:`_expression.Select` and then join that subquery to the
 |         target.
 |
 |         This is a **backwards incompatible change** as the previous behavior
 |         was mostly useless, producing an unnamed subquery rejected by
 |         most databases in any case.   The new behavior is modeled after
 |         that of the very successful :meth:`_orm.Query.join` method in the
 |         ORM, in order to support the functionality of :class:`_orm.Query`
 |         being available by using a :class:`_sql.Select` object with an
 |         :class:`_orm.Session`.
 |
 |         See the notes for this change at :ref:`change_select_join`.
 |
 |      .. seealso::
 |
 |          :ref:`tutorial_select_join` - in the :doc:`/tutorial/index`
 |
 |          :ref:`orm_queryguide_joins` - in the :ref:`queryguide_toplevel`
 |
 |          :meth:`_expression.Select.join`
 |
 |  outerjoin_from(self, from_, target, onclause=None, full=False)
 |      Create a SQL LEFT OUTER JOIN against this :class:`_expression.Select`
 |      object's criterion
 |      and apply generatively, returning the newly resulting
 |      :class:`_expression.Select`.
 |
 |      Usage is the same as that of :meth:`_selectable.Select.join_from`.
 |
 |  reduce_columns(self, only_synonyms=True)
 |      Return a new :func:`_expression.select` construct with redundantly
 |      named, equivalently-valued columns removed from the columns clause.
 |
 |      "Redundant" here means two columns where one refers to the
 |      other either based on foreign key, or via a simple equality
 |      comparison in the WHERE clause of the statement.   The primary purpose
 |      of this method is to automatically construct a select statement
 |      with all uniquely-named columns, without the need to use
 |      table-qualified labels as
 |      :meth:`_expression.Select.set_label_style`
 |      does.
 |
 |      When columns are omitted based on foreign key, the referred-to
 |      column is the one that's kept.  When columns are omitted based on
 |      WHERE equivalence, the first column in the columns clause is the
 |      one that's kept.
 |
 |      :param only_synonyms: when True, limit the removal of columns
 |       to those which have the same name as the equivalent.   Otherwise,
 |       all columns that are equivalent to another are removed.
 |
 |  select_from(self, *froms)
 |      Return a new :func:`_expression.select` construct with the
 |      given FROM expression(s)
 |      merged into its list of FROM objects.
 |
 |      E.g.::
 |
 |          table1 = table('t1', column('a'))
 |          table2 = table('t2', column('b'))
 |          s = select(table1.c.a).\
 |              select_from(
 |                  table1.join(table2, table1.c.a==table2.c.b)
 |              )
 |
 |      The "from" list is a unique set on the identity of each element,
 |      so adding an already present :class:`_schema.Table`
 |      or other selectable
 |      will have no effect.   Passing a :class:`_expression.Join` that refers
 |      to an already present :class:`_schema.Table`
 |      or other selectable will have
 |      the effect of concealing the presence of that selectable as
 |      an individual element in the rendered FROM list, instead
 |      rendering it into a JOIN clause.
 |

In [239]:
stmt = select(*entities)
# if not end_date:
#     end_date = start_date
    
# if start_date:
stmt = stmt.where(between(models.Volte.base_date, "20220501", "20220503"))

stmt = stmt.where(models.Volte.oper_team_nm == "성남엔지니어링부")

stmt = stmt.group_by(*entities[:-5]).order_by(cut_ratio.desc())
query_result = db.execute(stmt).fetchmany(size=30)

In [240]:
query_result

[('(공동)사병폰_특전사4LRRU(B7)', '경기도오포읍 매산리', '성남엔지니어링부', '성남3조', 3, 3, 0, 1, 33.3333),
 ('백현동_알파돔시티6-1블럭03-공용-SKT_8TD_F', '경기도백현동', '성남엔지니어링부', '성남2조', 14, 9, 5, 2, 22.2222),
 ('광주검단산중-1_LRIU_TN_900', '경기도남한산성면 산성리', '성남엔지니어링부', '성남3조', 11, 10, 1, 2, 20.0),
 ('(공동)신현리능골LD1RU2(3B7)', '경기도오포읍 능평리', '성남엔지니어링부', '성남3조', 8, 6, 2, 1, 16.6667),
 ('고등동_제일풍경채107동_32T_B', '경기도고등동', '성남엔지니어링부', '성남1조', 8, 6, 2, 1, 16.6667),
 ('매룡동_196-1전주_32T_B', '경기도매룡동', '성남엔지니어링부', '성남5조', 12, 6, 6, 1, 16.6667),
 ('단대동_단대푸르지오상가앞_32T_B', '경기도단대동', '성남엔지니어링부', '성남1조', 13, 12, 1, 2, 16.6667),
 ('팜스케어켐핑장옥외펨토900', '경기도능현동', '성남엔지니어링부', '성남5조', 8, 6, 2, 1, 16.6667),
 ('월송동_세종팰리스앞전주_32T_B', '경기도월송동', '성남엔지니어링부', '성남5조', 8, 7, 1, 1, 14.2857),
 ('목현동_이배재터널_8T_F', '경기도목현동', '성남엔지니어링부', '성남3조', 10, 8, 2, 1, 12.5),
 ('백현동_알파돔시티6-1블럭01-공용-SKT_8TD_D', '경기도백현동', '성남엔지니어링부', '성남2조', 29, 25, 4, 3, 12.0),
 ('태평동_태양오피스텔_32T_C', '경기도태평동', '성남엔지니어링부', '성남1조', 22, 20, 2, 2, 10.0),
 ('수진동_수진동663-1_32T_C', '경기도수진동', '성남엔지니어링부', '성남1조', 13, 11, 2, 1, 9.0909),
 ('감곡면_극동대학교보건관옥상_32T_B', '충청북도감곡면 왕장리', '성남엔지니어링부', '충북1조', 14, 11, 3, 1, 9.0909),
 ('도촌동_도촌동우체국_32T_A', '경기도도촌동', '성남엔지니어링부', '성남1조', 15, 11, 4, 1, 9.0909),
 ('성남한라시그마밸리_MHUTN', '경기도수진동', '성남엔지니어링부', '성남1조', 96, 80, 16, 7, 8.75),
 ('상대원동_상대원동822-9_32T_C', '경기도상대원동', '성남엔지니어링부', '성남1조', 19, 12, 7, 1, 8.3333),
 ('태전동_태전힐스테이트1610동_32T_C', '경기도태전동', '성남엔지니어링부', '성남3조', 16, 12, 4, 1, 8.3333),
 ('점봉동_세종그랑시아입구전주_32T_C', '경기도점봉동', '성남엔지니어링부', '성남5조', 19, 12, 7, 1, 8.3333),
 ('설봉공원영월암전주', '경기도관고동', '성남엔지니어링부', '성남4조', 33, 26, 7, 2, 7.6923),
 ('백현동_알파돔시티6-1블럭07-공용-SKT_8TD_D', '경기도백현동', '성남엔지니어링부', '성남2조', 36, 26, 10, 2, 7.6923),
 ('쌍령동_광주센트럴푸르지오111동_32T_A', '경기도쌍령동', '성남엔지니어링부', '성남3조', 17, 13, 4, 1, 7.6923),
 ('삼평동_경기창조경제혁신센터_32T_A', '경기도삼평동', '성남엔지니어링부', '성남2조', 28, 26, 2, 2, 7.6923),
 ('태전동_태전동거명빌라_32T_B', '경기도태전동', '성남엔지니어링부', '성남3조', 21, 14, 7, 1, 7.1429),
 ('태평동_태평4동7297_32T_B', '경기도태평동', '성남엔지니어링부', '성남1조', 26, 14, 12, 1, 7.1429),
 ('정자동_네이버2사옥06_8TD_D', '경기도정자동', '성남엔지니어링부', '성남2조', 16, 14, 2, 1, 7.1429),
 ('태평동_중앙교회_32T_B', '경기도태평동', '성남엔지니어링부', '성남1조', 22, 14, 8, 1, 7.1429),
 ('태평동6665UROUTN', '경기도태평동', '성남엔지니어링부', '성남1조', 75, 57, 18, 4, 7.0175),
 ('천송동_경기철강_32T_B', '경기도천송동', '성남엔지니어링부', '성남5조', 17, 15, 2, 1, 6.6667),
 ('(공동)(고)상번천리LRRUM', '경기도남한산성면 상번천리', '성남엔지니어링부', '성남3조', 19, 15, 4, 1, 6.6667)]

In [235]:
test = select(*entities[:-3], models.Volte.wjxbfs1, models.Volte.wjxbfs2, models.Volte.wjxbfs3, func.nvl(models.Volte.wjxbfs4, 0)).where(models.Volte.equip_nm=="(공동)사병폰_특전사4LRRU(B7)")
print(db.execute(test).all())

[('(공동)사병폰_특전사4LRRU(B7)', '경기도오포읍 매산리', '성남엔지니어링부', '성남3조', 3, 3, None, 1)]

In [149]:
print(query_result)

[('20220501', '상대원동_오리엔트시계_32T_A', '경기도상대원동', '성남엔지니어링부', '성남1조', 100.0), ('20220501', '(공동)신현리능골LD1RU2(3B7)', '경기도오포읍 능평리', '성남엔지니어링부', '성남3조', 100.0), ('20220501', '백사면신영케미텍_FEMTO', '경기도백사면 경사리', '성남엔지니어링부', '성남4조', 100.0), ('20220503', '광주검단산중-1_LRIU_TN_900', '경기도남한산성면 산성리', '성남엔지니어링부', '성남3조', 50.0), ('20220501', '(공동)사병폰_특전사4LRRU(B7)', '경기도오포읍 매산리', '성남엔지니어링부', '성남3조', 33.3333), ('20220501', '금광동_신구대동관_32T_B', '경기도금광동', '성남엔지니어링부', '성남1조', 33.3333), ('20220502', '팜스케어켐핑장옥외펨토900', '경기도능현동', '성남엔지니어링부', '성남5조', 33.3333), ('20220502', '매룡동_196-1전주_32T_B', '경기도매룡동', '성남엔지니어링부', '성남5조', 33.3333), ('20220501', '(공동)도척탄약대SLRRU', '경기도도척면 방도리', '성남엔지니어링부', '성남3조', 28.5714), ('20220503', '단대동_단대푸르지오상가앞_32T_B', '경기도단대동', '성남엔지니어링부', '성남1조', 28.5714)]

In [241]:
db.execute(stmt).fetchmany(size=5)

[(Decimal('0.3765'),),
 (Decimal('0.3923'),),
 (Decimal('0.3338'),),
 (Decimal('0.2587'),),
 (Decimal('0.3225'),)]

In [210]:
voc_cnt = func.sum(models.VocList.wjxbfs1).label("voc_cnt")
juso = func.concat(models.VocList.sido_nm, models.VocList.eup_myun_dong_nm).label("juso")
stmt = select(models.VocList.base_ym,
              models.VocList.base_date,
              models.VocList.equip_cd0,
              juso,
              models.VocList.bts_oper_team_nm,
              models.VocList.adm_cd1,
              voc_cnt).where(models.VocList.base_date =="20220531")\
              .group_by(models.VocList.base_ym,
              models.VocList.base_date,
              models.VocList.equip_cd0,
              juso,
              models.VocList.bts_oper_team_nm,
              models.VocList.adm_cd1).order_by(voc_cnt.desc())
print(stmt)

SELECT dashboard_voc_list.base_ym, dashboard_voc_list.base_date, dashboard_voc_list.equip_cd0, concat(dashboard_voc_list.sido_nm, dashboard_voc_list.eup_myun_dong_nm) AS juso, dashboard_voc_list.bts_oper_team_nm, dashboard_voc_list.adm_cd1, sum(dashboard_voc_list.wjxbfs1) AS voc_cnt
FROM dashboard_voc_list
WHERE dashboard_voc_list.base_date = :base_date_1 GROUP BY dashboard_voc_list.base_ym, dashboard_voc_list.base_date, dashboard_voc_list.equip_cd0, concat(dashboard_voc_list.sido_nm, dashboard_voc_list.eup_myun_dong_nm), dashboard_voc_list.bts_oper_team_nm, dashboard_voc_list.adm_cd1 ORDER BY voc_cnt DESC

In [170]:
print(select(models.VocList))

SELECT dashboard_voc_list.lte_only, dashboard_voc_list.hndset_pet_nm, dashboard_voc_list.aed_div_itg_cd, dashboard_voc_list.sa_5g_suprt_div_nm, dashboard_voc_list.voc_wjt_prmr_sorc_id, dashboard_voc_list.voc_wjt_prmr_nm, dashboard_voc_list.voc_wjt_scnd_sorc_id, dashboard_voc_list.voc_wjt_scnd_nm, dashboard_voc_list.voc_wjt_tert_sorc_id, dashboard_voc_list.voc_wjt_tert_nm, dashboard_voc_list.voc_wjt_qrtc_sorc_id, dashboard_voc_list.voc_wjt_qrtc_nm, dashboard_voc_list.voc_type_itg_cd, dashboard_voc_list.voc_type_nm, dashboard_voc_list.sr_tt_rcp_no, dashboard_voc_list.custcol_56, dashboard_voc_list.volte_out_cmplt_yn, dashboard_voc_list.equip_cd, dashboard_voc_list.bprod_sbt_id_m, dashboard_voc_list.bprod_nm, dashboard_voc_list.custcol_70, dashboard_voc_list.base_ym, dashboard_voc_list.base_date, dashboard_voc_list.bts_biz_hq_cd, dashboard_voc_list.bts_biz_hq_nm, dashboard_voc_list.hndset_model_sbt_id, dashboard_voc_list.hndset_model_nm, dashboard_voc_list.band_nm, dashboard_voc_list.anals_5_prod_level_id, dashboard_voc_list.anals_5_prod_level_nm, dashboard_voc_list.custcol_57, dashboard_voc_list.svc_cont_id, dashboard_voc_list.sbt_bts_cd, dashboard_voc_list.gun_gu_nm, dashboard_voc_list.sido_nm, dashboard_voc_list.pricng_div_5_lvl, dashboard_voc_list.oper_team_cd, dashboard_voc_list.bts_oper_team_nm, dashboard_voc_list.eup_myun_dong_nm, dashboard_voc_list.trobl_rgn_adr_sbst, dashboard_voc_list.trobl_rgn_dtl_sbst, dashboard_voc_list.equip_cd0, dashboard_voc_list.adm_cd, dashboard_voc_list.adm_cd0, dashboard_voc_list.adm_cd1, dashboard_voc_list.adm_cd2, dashboard_voc_list.wjxbfs1
FROM dashboard_voc_list

In [172]:
print(func.sum(case(value=models.VocList.wjxbfs1, whens={3:1}, else_=0)))

sum(CASE dashboard_voc_list.wjxbfs1 WHEN :param_1 THEN :param_2 ELSE :param_3 END)

In [57]:
voc_cnt = func.case(
                    (func.sum(models.VocList.wjxbfs1) > 0, func.sum(models.VocList.wjxbfs1)),
                    else_=0
)

In [49]:
print(func.sum(case(value=models.VocList.wjxbfs1, whens={"sum(wjxbfs1) > 0":"sum(wjxbfs1)"}, else_=0)).label("voc_cnt"))

sum(CASE dashboard_voc_list.wjxbfs1 WHEN :param_1 THEN :param_2 ELSE :param_3 END)

In [110]:
entities = [
        models.VocList.base_ym,
        models.VocList.base_date,
        models.VocList.equip_cd0,
        juso,
        models.VocList.bts_oper_team_nm,
        models.VocList.adm_cd1,
        voc_cnt
    ]
stmt = select(*entities)

In [116]:
# print(stmt.where(between(models.Voc.base_date, 1,2)))

SELECT dashboard_voc_list.base_ym, dashboard_voc_list.base_date, dashboard_voc_list.equip_cd0, concat(dashboard_voc_list.sido_nm, dashboard_voc_list.eup_myun_dong_nm) AS juso, dashboard_voc_list.bts_oper_team_nm, dashboard_voc_list.adm_cd1, sum(dashboard_voc_list.wjxbfs1) AS voc_cnt
FROM dashboard_voc_list, dashboard_freq_voc_tb_dd
WHERE dashboard_freq_voc_tb_dd.base_date BETWEEN :base_date_1 AND :base_date_2

In [117]:
stmt = stmt.where(between(base_date, start_date, end_date))

SELECT dashboard_voc_list.base_ym, dashboard_voc_list.base_date, dashboard_voc_list.equip_cd0, concat(dashboard_voc_list.sido_nm, dashboard_voc_list.eup_myun_dong_nm) AS juso, dashboard_voc_list.bts_oper_team_nm, dashboard_voc_list.adm_cd1, sum(dashboard_voc_list.wjxbfs1) AS voc_cnt
FROM dashboard_voc_list

In [159]:
# Group code: 1: 조, 2: 팀, 3: 센터, 4: 본부
# Date code: 1: 일, 2: 주, 3: 월
def get_voc_group_by_group_date(filter_group, start_date=None, end_date=None):
    voc_cnt = func.sum(models.VocList.wjxbfs1).label("voc_cnt")
    juso = func.concat(models.VocList.sido_nm, models.VocList.eup_myun_dong_nm).label("juso")
    entities = [
        models.VocList.base_ym,
        models.VocList.base_date,
        models.VocList.equip_cd0,
        juso,
        models.VocList.bts_oper_team_nm,
        models.VocList.adm_cd1,
        voc_cnt
    ]
    stmt = select(*entities)
    
    if not end_date:
        end_date = start_date
        
    if start_date:
        stmt = stmt.where(between(models.VocList.base_date, start_date, end_date))
    
    if filter_group:
        stmt = stmt.where(models.VocList.bts_oper_team_nm == filter_group)
    
    stmt = stmt.group_by(models.VocList.base_ym,
                         models.VocList.base_date,
                         models.VocList.equip_cd0,
                         juso,
                         models.VocList.bts_oper_team_nm,
                         models.VocList.adm_cd1).order_by(voc_cnt.desc())
    return stmt

In [165]:
rst = get_voc_group_by_group_date(filter_group="구로엔지니어링부", start_date="20220511", end_date="20220521")
print(db.execute(rst).fetchmany(size=10)[0])

('202205', '20220517', '상도동_숭실대둘레길-T(900M)', '서울특별시상도동', '구로엔지니어링부', '구로2조', 2)

In [133]:
print(rst)

SELECT dashboard_voc_list.base_ym, dashboard_voc_list.base_date, dashboard_voc_list.equip_cd0, concat(dashboard_voc_list.sido_nm, dashboard_voc_list.eup_myun_dong_nm) AS juso, dashboard_voc_list.bts_oper_team_nm, dashboard_voc_list.adm_cd1, sum(dashboard_voc_list.wjxbfs1) AS voc_cnt
FROM dashboard_voc_list
WHERE dashboard_voc_list.base_date BETWEEN :base_date_1 AND :base_date_2 AND dashboard_voc_list.bts_oper_team_nm = :bts_oper_team_nm_1 GROUP BY dashboard_voc_list.base_ym, dashboard_voc_list.base_date, dashboard_voc_list.equip_cd0, concat(dashboard_voc_list.sido_nm, dashboard_voc_list.eup_myun_dong_nm), dashboard_voc_list.bts_oper_team_nm, dashboard_voc_list.adm_cd1 ORDER BY voc_cnt DESC

In [180]:
from datetime import datetime, timedelta

In [196]:
today = (datetime.today() - timedelta(30)).strftime("%Y%m%d")
yesterday = (datetime.today() - timedelta(31)).strftime("%Y%m%d")
in_cond = [yesterday, today]

In [197]:
voc_cnt = func.sum(models.VocList.wjxbfs1).label("voc_cnt")
entities = [
        models.VocList.base_date,
        models.VocList.bts_oper_team_nm,
        voc_cnt
    ]

In [204]:
stmt = select(entities, models.VocList.base_date.in_(in_cond)).where(models.VocList.bts_oper_team_nm == "성남엔지니어링부").group_by(*entities[:-1]).order_by(models.VocList.base_date.asc())

In [205]:
db.execute(stmt).all()

[('20220522', '성남엔지니어링부', 1), ('20220523', '성남엔지니어링부', 4)]